#!/usr/bin/env bash
set -euo pipefail

# Provisions (or reuses) an EC2 instance tagged with EC2_INSTANCE_NAME.
# Writes connection details to deploy.state for use by the Makefile.

AWS_REGION="${AWS_REGION:-us-east-1}"
EC2_INSTANCE_NAME="${EC2_INSTANCE_NAME:-freelance-job-agent}"
EC2_INSTANCE_TYPE="${EC2_INSTANCE_TYPE:-t4g.micro}"
EC2_SSH_USER="${EC2_SSH_USER:-ec2-user}"
SG_NAME="${EC2_SG_NAME:-${EC2_INSTANCE_NAME}-sg}"
STATE_FILE="${DEPLOY_STATE_FILE:-deploy.state}"

require() {
  local name="$1"
  local value="$2"
  if [[ -z "${value}" ]]; then
    echo "error: ${name} is required" >&2
    exit 1
  fi
}

require "AWS_KEY_NAME" "${AWS_KEY_NAME:-}"
require "SSH_KEY" "${SSH_KEY:-}"

if [[ ! -f "${SSH_KEY/#\~/$HOME}" ]]; then
  echo "error: SSH_KEY file not found: ${SSH_KEY}" >&2
  exit 1
fi

export AWS_DEFAULT_REGION="${AWS_REGION}"
export AWS_REGION="${AWS_REGION}"

echo "==> Checking AWS credentials (region: ${AWS_REGION})"
aws sts get-caller-identity >/dev/null

if [[ -z "${MY_IP:-}" ]]; then
  echo "==> Detecting public IP"
  MY_IP="$(curl -fsS https://checkip.amazonaws.com | tr -d '[:space:]')"
  echo "    MY_IP=${MY_IP}"
fi

pick_ami() {
  local arch_param
  if [[ "${EC2_INSTANCE_TYPE}" == *g.* ]]; then
    arch_param="/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64"
  else
    arch_param="/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
  fi
  aws ssm get-parameters \
    --names "${arch_param}" \
    --query "Parameters[0].Value" \
    --output text
}

find_instance_id() {
  aws ec2 describe-instances \
    --filters \
      "Name=tag:Name,Values=${EC2_INSTANCE_NAME}" \
      "Name=instance-state-name,Values=pending,running,stopping,stopped" \
    --query "Reservations[].Instances[] | sort_by(@, &LaunchTime) | [-1].InstanceId" \
    --output text 2>/dev/null | tr -d '[:space:]'
}

ensure_security_group() {
  local vpc_id sg_id
  vpc_id="$(aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query "Vpcs[0].VpcId" --output text)"
  if [[ -z "${vpc_id}" || "${vpc_id}" == "None" ]]; then
    echo "error: no default VPC found in ${AWS_REGION}" >&2
    exit 1
  fi

  sg_id="$(aws ec2 describe-security-groups \
    --filters "Name=group-name,Values=${SG_NAME}" "Name=vpc-id,Values=${vpc_id}" \
    --query "SecurityGroups[0].GroupId" \
    --output text 2>/dev/null || true)"

  if [[ -z "${sg_id}" || "${sg_id}" == "None" ]]; then
    echo "==> Creating security group ${SG_NAME}" >&2
    sg_id="$(aws ec2 create-security-group \
      --group-name "${SG_NAME}" \
      --description "SSH access for ${EC2_INSTANCE_NAME}" \
      --vpc-id "${vpc_id}" \
      --query "GroupId" \
      --output text)"
  else
    echo "==> Reusing security group ${SG_NAME} (${sg_id})" >&2
  fi

  echo "==> Ensuring SSH (22) from ${MY_IP}/32" >&2
  aws ec2 authorize-security-group-ingress \
    --group-id "${sg_id}" \
    --protocol tcp \
    --port 22 \
    --cidr "${MY_IP}/32" 2>/dev/null || true

  echo "${sg_id}"
}

wait_for_running() {
  local instance_id="$1"
  echo "==> Waiting for instance ${instance_id} to be running"
  aws ec2 wait instance-running --instance-ids "${instance_id}"
  echo "==> Waiting for status checks"
  aws ec2 wait instance-status-ok --instance-ids "${instance_id}" || true
}

get_public_ip() {
  local instance_id="$1"
  aws ec2 describe-instances \
    --instance-ids "${instance_id}" \
    --query "Reservations[0].Instances[0].PublicIpAddress" \
    --output text
}

write_state() {
  local instance_id="$1"
  local public_ip="$2"
  local goarch="arm64"

  if [[ "${EC2_INSTANCE_TYPE}" != *g.* ]]; then
    goarch="amd64"
  fi

  cat > "${STATE_FILE}" <<EOF
# Generated by scripts/provision-ec2.sh — do not commit
EC2_HOST=${EC2_SSH_USER}@${public_ip}
EC2_INSTANCE_ID=${instance_id}
GOARCH_LINUX=${goarch}
EOF

  echo "==> Wrote ${STATE_FILE}"
  echo "    EC2_HOST=${EC2_SSH_USER}@${public_ip}"
  echo "    EC2_INSTANCE_ID=${instance_id}"
  echo "    GOARCH_LINUX=${goarch}"
}

instance_id="$(find_instance_id)"

if [[ -n "${instance_id}" && "${instance_id}" != "None" ]]; then
  state="$(aws ec2 describe-instances \
    --instance-ids "${instance_id}" \
    --query "Reservations[0].Instances[0].State.Name" \
    --output text)"

  echo "==> Found existing instance ${instance_id} (state: ${state})"

  if [[ "${state}" == "stopped" ]]; then
    echo "==> Starting stopped instance"
    aws ec2 start-instances --instance-ids "${instance_id}" >/dev/null
    wait_for_running "${instance_id}"
  elif [[ "${state}" == "stopping" ]]; then
    echo "==> Instance is stopping — waiting before start"
    aws ec2 wait instance-stopped --instance-ids "${instance_id}"
    aws ec2 start-instances --instance-ids "${instance_id}" >/dev/null
    wait_for_running "${instance_id}"
  elif [[ "${state}" == "pending" ]]; then
    wait_for_running "${instance_id}"
  fi
else
  echo "==> No instance found — creating ${EC2_INSTANCE_NAME}"
  ami_id="$(pick_ami)"
  sg_id="$(ensure_security_group)"

  echo "==> Launching ${EC2_INSTANCE_TYPE} with AMI ${ami_id}"
  instance_id="$(aws ec2 run-instances \
    --image-id "${ami_id}" \
    --instance-type "${EC2_INSTANCE_TYPE}" \
    --key-name "${AWS_KEY_NAME}" \
    --security-group-ids "${sg_id}" \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${EC2_INSTANCE_NAME}}]" \
    --block-device-mappings '[{"DeviceName":"/dev/xvda","Ebs":{"VolumeSize":10,"DeleteOnTermination":true,"VolumeType":"gp3"}}]' \
    --query "Instances[0].InstanceId" \
    --output text)"

  wait_for_running "${instance_id}"
fi

public_ip="$(get_public_ip "${instance_id}")"
if [[ -z "${public_ip}" || "${public_ip}" == "None" ]]; then
  echo "error: instance ${instance_id} has no public IP — assign an Elastic IP or enable public IP on launch" >&2
  exit 1
fi

write_state "${instance_id}" "${public_ip}"
